version: '3.4'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 8080:80
            - 8443:443
        volumes:
                - ../www:/var/www/html:z
                - ../api:/var/www/api:z
        environment: 
            CRLIBRE_API_HACIENDA_DB_HOST: 'mariadb'                   # 
            CRLIBRE_API_HACIENDA_DB_NAME: 'testdb'                    # 
            CRLIBRE_API_HACIENDA_DB_USER: 'testuser'                  # 
            CRLIBRE_API_HACIENDA_DB_PASSWORD: 'testpassword'          # 
        # restart: always
        # tty: true
        depends_on:
            - 'mariadb'
        links:
            - 'mariadb:database'
    mariadb:
        image: mariadb:10.1
        ports:
            - 4407:3306
        volumes:
            - mariadb:/var/lib/mysql
            - ../recursos/sql:/docker-entrypoint-initdb.d
            # - ../recursos/sql:/tmp/deployment/sql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'
        restart: always
        tty: true
volumes:
    mariadb: